#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.13"
# dependencies = ["pyyaml>=6", "websockets>=13"]
# ///
"""Read tier-2 state back out of the instance as normalised YAML.

Dashboards, helpers and the entity/device/area/floor/label registries live in
`.storage` and never touch a file this repo tracks. Pulling them into
`exports/<instance>/` gives the one thing Home Assistant otherwise has no answer
for: a diff. `mise run drift` turns that diff into a signal that something
changed outside the repo — usually a UI edit from a phone.

Read-only. Nothing here writes to the instance.

Three rules this script exists to obey:

  Sort deterministically.  Home Assistant's iteration order is not stable, so
  without a stable sort key every pull rewrites every file and the diff stops
  meaning anything. Sort keys are the natural stable ones — unique_id for
  entities, and the registry id elsewhere — never a display name, which would
  reshuffle the whole file on a rename.

  Whitelist fields, never blacklist.  `core.config_entries` holds integration
  credentials in plaintext. A blacklist fails open the first time an
  integration adds a field nobody thought about, so every exporter here names
  what it keeps.

  Emit nothing that changes on its own.  No timestamps, no `modified_at`, no
  HACS `available_version`. Anything that moves without a human moving it turns
  drift detection into noise and trains people to ignore it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Iterable

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from ha_api import HaApiError  # noqa: E402
from ha_ws import HaWs  # noqa: E402

EXPORTS_ROOT = Path(__file__).resolve().parent.parent.parent / "exports"

HEADER = (
    "# Generated by tools/pull. Never hand-edit, never deploy from this file.\n"
    "# `desired/` is what you write; `exports/` is what the instance actually has.\n"
)

# --- field whitelists ------------------------------------------------------
#
# Timestamps (created_at / modified_at) are excluded everywhere: they change
# without anyone changing configuration, which is exactly the churn that makes a
# drift diff worthless.

ENTITY_FIELDS = (
    "unique_id",
    "entity_id",
    "platform",
    "name",
    "original_name",
    "icon",
    "area_id",
    "device_id",
    "entity_category",
    "disabled_by",
    "hidden_by",
    "labels",
    "categories",
    "options",
)

# sw_version, hw_version and serial_number are deliberately absent. Firmware
# versions are runtime facts, not configuration, and an ESPHome fleet updating
# itself would bury every real change under version churn.
DEVICE_FIELDS = (
    "id",
    "name",
    "name_by_user",
    "manufacturer",
    "model",
    "model_id",
    "area_id",
    "entry_type",
    "disabled_by",
    "labels",
    "identifiers",
    "via_device_id",
    "configuration_url",
)

AREA_FIELDS = (
    "area_id",
    "name",
    "floor_id",
    "icon",
    "aliases",
    "labels",
    "temperature_entity_id",
    "humidity_entity_id",
)

FLOOR_FIELDS = ("floor_id", "name", "level", "icon", "aliases")

LABEL_FIELDS = ("label_id", "name", "icon", "color", "description")

# Domain and title only. Everything else in a config entry is either an opaque
# instance-local id or, in `data`, the integration's credentials.
CONFIG_ENTRY_FIELDS = ("domain", "title")

# available_version is upstream news, not local state: it moves when a
# maintainer tags a release, which would show up as drift nobody caused.
HACS_FIELDS = ("full_name", "name", "category", "domain", "installed_version")

DASHBOARD_META_FIELDS = (
    "id",
    "title",
    "url_path",
    "icon",
    "mode",
    "require_admin",
    "show_in_sidebar",
)


def keep(record: dict, fields: Iterable[str]) -> dict:
    """Project a record onto the whitelisted fields, dropping empties.

    Empty values are dropped so that an integration adding a field it never
    populates does not rewrite every record in the file.
    """
    return {
        field: record[field]
        for field in fields
        if record.get(field) not in (None, "", [], {})
    }


def dump(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(
        payload,
        sort_keys=True,
        default_flow_style=False,
        allow_unicode=True,
        width=100,
    )
    path.write_text(HEADER + body)


def sorted_by(records: list[dict], *keys: str) -> list[dict]:
    """Sort on stable identifiers, never on anything a human renames."""

    def sort_key(record: dict) -> tuple:
        return tuple(str(record.get(key) or "") for key in keys)

    return sorted(records, key=sort_key)


# --- exporters -------------------------------------------------------------


def pull_registry(ws: HaWs, out: Path) -> str:
    entities = ws.command("config/entity_registry/list")
    devices = ws.command("config/device_registry/list")
    areas = ws.command("config/area_registry/list")
    floors = ws.command("config/floor_registry/list")
    labels = ws.command("config/label_registry/list")

    payload = {
        # unique_id is the registry's stable natural key and survives a rename;
        # entity_id breaks the tie when two platforms share a unique_id.
        "entities": [
            keep(e, ENTITY_FIELDS) for e in sorted_by(entities, "unique_id", "entity_id")
        ],
        "devices": [keep(d, DEVICE_FIELDS) for d in sorted_by(devices, "id")],
        "areas": [keep(a, AREA_FIELDS) for a in sorted_by(areas, "area_id")],
        "floors": [keep(f, FLOOR_FIELDS) for f in sorted_by(floors, "floor_id")],
        "labels": [keep(l, LABEL_FIELDS) for l in sorted_by(labels, "label_id")],
    }
    dump(out / "registry.yaml", payload)
    return (
        f"registry.yaml: {len(entities)} entities, {len(devices)} devices, "
        f"{len(areas)} areas, {len(floors)} floors, {len(labels)} labels"
    )


def pull_config_entries(ws: HaWs, out: Path) -> str:
    entries = ws.command("config_entries/get")
    payload = [keep(e, CONFIG_ENTRY_FIELDS) for e in sorted_by(entries, "domain", "title")]
    dump(out / "config_entries.yaml", payload)
    return f"config_entries.yaml: {len(payload)} entries (domain and title only)"


def pull_hacs(ws: HaWs, out: Path) -> str:
    repositories = ws.try_command("hacs/repositories/list")
    if repositories is None:
        return "hacs.yaml: skipped, HACS not available on this instance"

    # The command returns the whole catalogue — nearly 4000 repositories, and
    # over the default WebSocket frame cap. Only what is installed is state.
    installed = [r for r in repositories if r.get("installed")]
    payload = [keep(r, HACS_FIELDS) for r in sorted_by(installed, "full_name")]
    dump(out / "hacs.yaml", payload)
    return f"hacs.yaml: {len(payload)} installed of {len(repositories)} in catalogue"


def pull_dashboards(ws: HaWs, out: Path) -> str:
    boards = ws.command("lovelace/dashboards/list")
    directory = out / "dashboards"
    written: set[Path] = set()
    skipped: list[str] = []

    for board in sorted_by(boards, "id"):
        url_path = board.get("url_path")

        # Home Assistant resolves !secret when it loads a YAML-mode dashboard,
        # so exporting one could write resolved secrets into the repo.
        if board.get("mode") != "storage":
            skipped.append(f"{board.get('id')} (mode={board.get('mode')})")
            continue

        config = ws.try_command("lovelace/config", url_path=url_path, force=False)
        if config is None:
            # Storage-mode but strategy-generated: nothing stored to export.
            skipped.append(f"{board.get('id')} (no stored config)")
            continue

        path = directory / f"{board['id']}.yaml"
        dump(path, {"dashboard": keep(board, DASHBOARD_META_FIELDS), "config": config})
        written.add(path)

    # A deleted dashboard has to disappear from exports/ too, or drift can
    # never show a deletion.
    removed = 0
    if directory.exists():
        for stale in directory.glob("*.yaml"):
            if stale not in written:
                stale.unlink()
                removed += 1

    message = f"dashboards/: {len(written)} written"
    if removed:
        message += f", {removed} stale removed"
    if skipped:
        message += f", skipped {', '.join(skipped)}"
    return message


EXPORTERS = {
    "registry": pull_registry,
    "config_entries": pull_config_entries,
    "hacs": pull_hacs,
    "dashboards": pull_dashboards,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "only",
        nargs="*",
        choices=[*EXPORTERS, []],
        help=f"limit to some exporters ({', '.join(EXPORTERS)}); default is all",
    )
    args = parser.parse_args()
    selected = args.only or list(EXPORTERS)

    try:
        with HaWs() as ws:
            out = EXPORTS_ROOT / ws.instance
            print(f"instance={ws.instance}  ->  {out.relative_to(EXPORTS_ROOT.parent.parent)}")
            for name in selected:
                print(f"  {EXPORTERS[name](ws, out)}")
    except HaApiError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    sys.exit(main())
